server:
  port: 8180
  context-path: /edge-service

security:
  oauth2:
    client:
      client-id: edge-service
      client-secret: secret
      user-authorization-uri: http://localhost:8080/authorization-service/oauth/authorize
      access-token-uri: http://localhost:8080/authorization-service/oauth/token
      grant-type: authorization_code, refresh_token
    resource:
      user-info-uri: http://localhost:8080/authorization-service/user/me
      token-info-uri: http://localhost:8080/authorization-service/oauth/check_token
      jwt:
        key-uri: http://localhost:8080/authorization-service/oauth/token_key